#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    disabled_plugins = ["phpfold.vim"]
    relativenumber = false
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "onedark"
    colorscheme = "molokai"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    filemanager = "nerdtree"
    bootstrap_after = "myconfig#after"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = "tools"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = "git"

[[layers]]
    name = "lsp"
    filetypes = [
        "php",
        "go"
    ]
    [layers.override_cmd]
        php = ["php", "~/.config/composer/vendor/felixfbecker/php-language-server/bin/php-language-server.php"]
        go = ["go-langserver", "-mode", "stdio"]

[[layers]]
    name = "lang#php"

[[layers]]
    name = "lang#go"

[[layers]]
    name = "ui"

#[[layers]]
#    name = "tags"

[[layers]]
    name = "lang#markdown"

